  'use strict';

  require('./anchor/plugin');
  require('./autolink/plugin');
  require('./code/plugin');
  require('./contextmenu/plugin');
  require('./directionality/plugin');
  require('./fullscreen/plugin');
  require('./hr/plugin');
  require('./image/plugin');
  require('./link/plugin');
  require('./lists/plugin');
  require('./magic/plugin');
  require('./nonbreaking/plugin');
  require('./pagebreak/plugin');
  require('./paste/plugin');
  require('./preview/plugin');
  require('./save/plugin');
  require('./searchreplace/plugin');
  require('./table/plugin');
  require('./template/plugin');
  require('./textcolor/plugin');
  require('./video/plugin');
  require('./visualblocks/plugin');
  require('./visualchars/plugin');
