language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-java-webapp' ]; then cd .. && eval "mv $currentfolder generator-java-webapp" && cd generator-java-webapp; fi

